apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
spec:
  chart:
    version: "9.2.2"
    values:
      global:
        hosts:
          domain: "workstation.co.uk" # use a real domain of your own here or localhost for testing
        ingress:
          configureCertmanager: true
      certmanager-issuer:
        email: balinder.walia@gmail.com # use your real email address here