gitlabUrl: ${GITLAB_URL}
runnerRegistrationToken: "${REGISTRATION_TOKEN}"
concurrent: ${RUNNER_CONCURRENT}
rbac:
  create: true
  clusterWideAccess: true
runners:
  privileged: true
  config: |
    [[runners]]
      environment = ["GIT_SSL_NO_VERIFY=1"]
      [runners.kubernetes]
        namespace = "gitlab-runner"
        image = "alpine/git:latest"
        helper_image = "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:${RUNNER_DOCKER_IMAGE_TAG}"
        helper_image_flavor = "alpine"
        service_account = "gitlab-runner"
        privileged = true
        [[runners.kubernetes.host_aliases]]
          ip = "CLUSTER_IP_PLACEHOLDER"
          hostnames = ["gitlab-webservice-default.gitlab-system.svc.cluster.local", "gitlab.workstation.co.uk","gitlab.local", "registry.local", "docker-registry.docker-registry.svc.cluster.local"]
        [[runners.kubernetes.services]]
          name = "docker"
          alias = "docker"
          image = "docker:24.0.6-dind"
          command = ["dockerd", "--host=tcp://0.0.0.0:2376", "--tls=false", "--insecure-registry=docker-registry.docker-registry.svc.cluster.local:5000", "--insecure-registry=docker-registry.docker-registry:5000", "--registry-mirror=https://mirror.gcr.io"]
          privileged = true
        [runners.kubernetes.dns_config]
          nameservers = ["10.43.0.10"]
          searches = ["gitlab-system.svc.cluster.local", "gitlab.svc.cluster.local", "docker-registry.svc.cluster.local", "default.svc.cluster.local", "svc.cluster.local", "cluster.local"]
        [[runners.kubernetes.volumes.secret]]
          name = "kubeconfig"
          mount_path = "/etc/kubeconfig"
          read_only = true
image:
  tag: alpine3.18-v16.11.1
