---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "test-minio-ingress-tls-{{ .Release.Namespace }}"  
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    tls.crt: {{ .Values.tlscrt }}
    tls.key: {{ .Values.tlskey }}
  template:
    metadata:
      name: "test-minio-ingress-tls-{{ .Release.Namespace }}"
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/tls
