apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.secrets.MINIO_ROOT_USER | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.MINIO_ROOT_PASSWORD | b64enc | quote }}
  MINIO_BROWSER_REDIRECT_URL: {{ .Values.secrets.MINIO_BROWSER_REDIRECT_URL | b64enc | quote }}
  MINIO_DEFAULT_BUCKETS: {{ .Values.secrets.MINIO_DEFAULT_BUCKETS | b64enc | quote }}