apiVersion: v1
kind: Service
metadata:
  name: test-minio-service-console
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: minio
  ports:
  - name: http
    port: 9001
    targetPort: 9001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: test-minio-service-cli
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: minio
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  type: ClusterIP