global:
  edition: ce
  hosts:
    domain: gitlab.local
    https: false
  ingress:
    configureCertmanager: false
    tls:
      enabled: false
  kas:
    enabled: false

# Disable optional subcharts the new way
certmanager:
  enabled: false

prometheus:
  enabled: false

gitlab-runner:
  enabled: false

# Use built-in nginx-ingress for local access
nginx-ingress:
  enabled: true
  controller:
    publishService:
      enabled: true

# Keep container registry but keep it light
registry:
  enabled: true
  hpa:
    enabled: false

# Tighter resources for laptop use
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitaly:
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi

postgresql:
  primary:
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi

redis:
  master:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
